### ISSUE TITLE
Err http://httpredir.debian.org jessie InRelease

### ISSUE THREAD

**Issue by Haitianisgood** [docker-library/rails#43] opened 2016-06-30 10:04 UTC
use Dockerfile
```
FROM ruby:2.3

# see update.sh for why all "apt-get install"s have to stay as one long line
RUN apt-get update && apt-get install -y nodejs --no-install-recommends && rm -rf /var/lib/apt/lists/*

# see http://guides.rubyonrails.org/command_line.html#rails-dbconsole
RUN apt-get update && apt-get install -y mysql-client --no-install-recommends && rm -rf /var/lib/apt/lists/*

ENV RAILS_VERSION 5.0.0.beta2

RUN gem sources --add https://ruby.taobao.org/ --remove https://rubygems.org/ && gem install rails --version "$RAILS_VERSION"

ENV BUNDLE_APP_CONFIG .bundle

RUN mkdir /data
WORKDIR /data
```
bulid command:

docker build  -t myrails  .

```
Sending build context to Docker daemon 19.97 kB
Step 1 : FROM ruby:2.3
 ---> e4b689e9dc8b
Step 2 : RUN apt-get update && apt-get install -y nodejs --no-install-recommends && rm -rf /var/lib/apt/lists/*
 ---> Running in 060f7b8d65f7
Err http://httpredir.debian.org jessie InRelease
  
Err http://httpredir.debian.org jessie-updates InRelease
  
Err http://security.debian.org jessie/updates InRelease
  
Err http://httpredir.debian.org jessie Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://httpredir.debian.org jessie-updates Release.gpg
  Could not resolve 'httpredir.debian.org'
Reading package lists...
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nodejs
The command '/bin/sh -c apt-get update && apt-get install -y nodejs --no-install-recommends && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

```
how can solve this probles......

**Comment by yosifkit** [comment] 2016-06-30 17:18
That looks like you are having a connection issue resolving `httpredir.debian.org`.  This is not really a problem with the image.  Perhaps you are behind a proxy and need to set `HTTP_PROXY` during the [build](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg)?

**Comment by virtualfunction** [comment] 2016-07-20 06:30
Debian's httpredir.debian.org generally causes random hell for me and it's a issue with docker / Debian in general - I've switched to using the alpine build which is way more reliable

**Comment by rac021** [comment] 2016-08-11 08:38
I also gets same error

**Closed** 2016-08-19 22:01 UTC

**Comment by PeterParker** [comment] 2017-07-19 19:29
Even changing to `deb.debian.org` (https://github.com/moby/moby/pull/27620) does not seem to solve this in my case.

For me, it appears the issue is proxy/firewall related.  A change in the firewall config for the host made by our admins appears to knock Docker out of kilter, and a `sudo service docker restart` seems to do the job after that.
